src/models.py

Delete call fails due to wrong arguments passed in the method call

Fix wrong method call

---

algoliasearch_django/__init__.py
algoliasearch_django/models.py
algoliasearch_django/registration.py
tests/test_signal.py

Here is my proposal for the limitation of `QuerySet.update()`. This method doesn't send signals so it's impossible for this module to update automatically the index on Algolia.
@redox proposed to subclass `QuerySet` and send signals for the `update()` method, however it will not work efficiently and would imply to subclass `models.Model` as well. I prefer a lighter approach.
Here is what the API looks like:
```python
>>> from algoliasearch_django import update_records
>>> qs = MyModel.objects.filter(myField=False)
>>> update_records(MyModel, qs, myField=True)
>>> # `update()` should be after `update_records` because here we filter and update the same field.
>>> qs.update(myField=True)
```
Instead of:
```python
>>> MyModel.objects.filter(myField=False).update(myField=True)
```
First, I'm …

Update multiple records with a QuerySet

---

src/models.py

model._meta.get_all_field_names() will be removed in django 1.10 and django 1.9 throughs a deprecation warning.

fix deprecation warning in django 1.9

---

src/models.py
src/version.py
tests/test_index.py

I have some models that have a valid geo location, but others that don't. This will prevent those models without a valid location from preventing indexing.

Check that geo_field callable returns something valid

---

src/models.py

We were not considering `custom_objectID` when removing 'id' from the
list of fields to index.

Do not hardcode 'id' in AlgoliaIndex

---

README.md
algoliasearch_django/registration.py
tests/test_engine.py

- Expose a reset method to reinitialize the AlgoliaEngine with optional new settings
- Test demonstrating reinitialization after overriding `AUTO_INDEXING` at test time 
- Improve docstrings

Reset method to leverage override_settings, solving #169 & #209

---

algoliasearch_django/models.py
tests/models.py
tests/test_index.py

Reopening #214 on a branch we control to add a test and fix the implementation.
>This will allow for use of `@property` fields to be used for the `objectID`

Add @property ObjectId support

---

algoliasearch_django/models.py
tests/models.py
tests/test_index.py

Hello there,
When `should_index` is not callable, both `reindex_all()` and `save_record()` are broken. Here is an attempt to fix it. I've used test-driven development to avoid any regression,
Cheers 👍

Fix reindex_all() and save_record() when should_index is not callable

---

ChangeLog
algoliasearch_django/version.py
release.sh
requirements.txt

The current release process stopped working as it was still targeting the legacy pypi.python.org.
I followed the recommandations in the [Migrating to Pypi.org guide](https://packaging.python.org/guides/migrating-to-pypi-org/?highlight=upgrading%20pypi), using `twine` instead of the [unsecure](https://pypi.python.org/pypi/twine#why-should-i-use-this) `setup.py upload` command.

Migrate release to twine

---

algoliasearch_django/models.py
tests/test_index.py

If a callable is used, it should be called for each and every instance as the result is supposed to vary between class instances.
An Algolia index has a `tags` class attribute (common to all instances). It should not be redefined in the index model code through an instance (see ``models.AlgoliaIndex.get_raw_record``)
because modifying a class attribute will have an impact on all instances (this is the difference between defining attributes in the class body and in the dunder __init__ method).
See issue for more context: https://github.com/algolia/algoliasearch-django/issues/228

Fix tags when using callable

---

algoliasearch_django/models.py
tests/test_index.py

From [this comment](https://github.com/algolia/algoliasearch-django/issues/238#issuecomment-363117562), `v1.5.4` did not fix the issue.
For now this PR contains two tests that should assert expected behavior:
- `test_reindex_no_settings` asserts that _without explicit settings definition, existing settings are kept across reindex_
- `test_reindex_with_settings` asserts that _with explicit settings definition, these settings are applied over reindex_
The next step is to get more info on the failing use case to compare with these tests.

Fix #238: reindex deletes settings (again)

---

.travis.yml
README.md
tox.ini

Despite the name of this PR, we were not compatible with python 3.3, since the [algoliasearch](https://github.com/algolia/algoliasearch-client-python) python package is not (dependency on the `requests` package).
So I just updated the readme and removed the tests concerning this version (who is not supported anymore according to the [pep-0398](https://www.python.org/dev/peps/pep-0398/#id21)

Drop support of Python 3.3

---

.travis.yml
tests/models.py
tests/test_commands.py
tox.ini

| New feature?      | no 
| Related Issue     | None
| Need Doc update   | no
So we are sure we are compatibles with the version stated in the README :)

fix(tests) Add tox envs for Django 1.10,1.11,2.0

---

ChangeLog
algoliasearch_django/version.py

Bump the version to 1.6.0:
* [FEAT] Auto-discover the index.py files

chore: Bump version to 1.6.0

---

algoliasearch_django/registration.py

We're adding the language version to all client.
Because in python we rely on `setExtraHeader`, the client version was lost, I'm adding it as well.

Add Python version and django version to UserAgent

---

requirements.txt
tests/factories.py
tests/test_signal.py
tox.ini

Some tests refactoring:
Next step will be to implement and use the `waitTask` from the python client, for the tests that really need to wait for the response from Algolia.

Test refactoring

---

algoliasearch_django/decorators.py
tests/test_decorators.py

- A new "context decorator" (a method decorator who can also act as a context manager) `disable_auto_indexing` was added. As it name imply, it is meant to temporary disable the auto indexing for a given model or for all models (the default behaviour). 
| New feature?      | yes
| Related Issue     | fix #251
| Need Doc update   | yes
A new `disable_auto_indexing` decorator / context manager was added.
In some cases, for big models operation, we want to temporary disable the auto-indexing feature.

feat(signals) Add a context decorator to disable the signals

---

ChangeLog
requirements.txt
setup.py

| Bug fix?          | yes
| Related Issue     | Fix #280 
| Need Doc update   | no
Since the version of `algoliasearch` is not specified on the requirements. When people perform `pip install algoliasearch-django`, pip will try to install the beta version of our client.
This pull request forces the installation of the `v1` of the `algoliasearch`.

Fixes non specified version of algoliasearch in requirements

---

algoliasearch_django/registration.py
requirements.txt
tests/test_index.py
tox.ini

**Description:**
A user reported an issue with a warning coming from our Django
codebase due to a deprecated call to our Python client
`client.set_extra_header`. This commit replaces this deprecated call
(since version `1.6.0` of our Python client, see commit
https://github.com/algolia/algoliasearch-client-python/commit/e6efb38ecd4c9f85df319c7eab5c317c68eab4da
for more details) with `client.set_extra_headers` instead. It also
ensures the requirements for our Python client is at least at version `1.6.0`.
**Testing plan:**
Running the regular test suite without any issue.

fix: prevent deprecation warning by removing deprecated call to set_extra_header

---

.travis.yml
tests/settings.py
tests/test_commands.py
tox.ini

| New feature?      | yes 
| Related Issue     | Fix https://github.com/algolia/algoliasearch-django/issues/287
| Need Doc update   | yes
This PR:
- adds tests for django 2.2LTS and django 3.x
- introduces the migration changes required to move from 1.x to 2.0, namely introduction of API: `MIDDLEWARES` and `Templates`. 
See file diff for line by line comments on changes. 
This confirms our Django integration test suite runs on 2.2LTS and current latest version: 3.x.
In a future PR, I think it would be sensible to deperecate all other versions than thoses currently supported.
Currently supported versions are **2.2 (LTS), 3.0 and 3.1**. This would make the test suite much lighter …

chore(test): test against django 2.2 compat

---

requirements.txt

| New feature?      | yes   
| Related Issue     | Fix https://github.com/algolia/algoliasearch-django/issues/298
| Need Doc update   | no
This updates the python client used to the latest major (>= 2.0).
Let's run on Travis the tests and see if anything breaks 😄 
It's not easy to use two different versions of the same library in python.
Using the Django integration got you stuck with the older version of the client.

chore(deps): update algoliasearch to latest major

---

README.md

| New feature?      | no    
| Related Issue     | N/A
| Need Doc update   | no
This clarifies the compatibility with Django 2.x and 3.x.
This is fully tests by the CI since this change: https://github.com/algolia/algoliasearch-django/pull/303

docs(compat): clarify compatibility with Django 2.x and 3.x

---

CONTRIBUTING.md

Adds to contributing guide steps to run the tests. Requested by @chloelbn

docs(contributing): add tests command to contributing guide

---

.travis.yml
algoliasearch_django/models.py
tox.ini

| Bug fix?          | yes
| New feature?      | no    
| Related Issue     | None  
| Need Doc update   | yes
- Added tests support for `Python3.8` and `Django3.2`.
- [edX/course-discovery](https://github.com/edx/course-discovery/) Django3.2 upgrade needs test support for Django32 in this package.

build: Add django 3.2 tests with python 3.6 and python 3.8

---

requirements.txt
setup.py
tox.ini

| Bug fix?          | yes
| New feature?      | no
| Related Issue     | Fix #328 
| Need Doc update   | yes
Algolia Search python client](https://pypi.org/project/algoliasearch/) recently released a version to support python 3.11 (algoliasearch 3.0.0). However, this algoliasearch-django requires algoliasearch<3.0 and >=2.0
Requirement constraint that needs updating for Python 3.11 compatibility.

feat: add support for Python 3.9, 3.10 and 3.11

---

algoliasearch_django/models.py
runtests.py
tests/test_index.py

🎟 Related Issue:
there is a regression in the new api clients, we don't remove the `highlightResult` anymore of the returned objects from the browse response.
in the meantime of a fix there, we can fix it in the integration to prevent different behaviors, as the API doesn't allow saving rules with `highlightResult`

fix: remove highlightResult from response
